TYPO3:
  FLOW3:
    persistence:
      backendOptions:
        driver: 'pdo_mysql'
        dbname: 'flow3' # adjust to your database name
        user: 'root'         # adjust to your database user
        password: 'flow3' # adjust to your database password
        host: 'localhost'    # adjust to your database host